data:
  env_data_path: '/kinova/data/'
  env_data_file: 'trainEnvironments.pkl'
  path_data_path: '/kinova/src/kinova-ros/MPNet/data/test/paths1/'
  path_data_file: 'path_data_sample.pkl'
  pointcloud_data_path: '/kinova/data/pcd/test/pcd/'
  targets_data_path: '/kinova/src/kinova-ros/MPNet/data/test/targets/'
  targets_data_file: 'kinova_test_targets.pkl'

model:
  model_path: '/kinova/src/kinova-ros/MPNet/bel_models/bel_40b/'
  mlp_model_name: 'mlp_PReLU_ae_dd199.pkl'
  enc_model_name: 'cae_encoder_199.pkl'
  dp: 0.9
  size: 1
  enc_input_size: 16053
  enc_output_size: 60
  mlp_input_size: 72
  mlp_output_size: 6

bel:
  numbits: 40
  nrange: 40
  code: 'u'

training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  num_paths: 1000
  filename: 'dataset_targets'

results:
  good_path_sample_path: '/kinova/src/kinova-ros/MPNet/path_samples_bel/good_path_samples/'
  bad_path_sample_path: '/kinova/src/kinova-ros/MPNet/path_samples_bel/bad_path_samples/'
  experiment_name: 'dual_baseline_sml_replan'
